# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: build and publish

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest  # Adjust the runner OS if required
    steps:
      - uses: actions/checkout@v3  # Fetch the repository code
      - name: Set up JDK 21  # Customize the JDK version as needed
        uses: actions/setup-java@v3
        with:
          java-version: '21'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle', 'gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Login to GitHub Packages (optional, only if required by your setup)
        run: echo ${{ secrets.GH_TOKEN }} | gh auth login --with-token

      - name: Build and publish with Gradle
        run: ./gradlew publish
